apiVersion: batch/v1
kind: CronJob
metadata:
  name: tide-app-cron
spec:
  schedule: "5 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tide-app
            image: gerops/tide-app:<tag>
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-secret
          
---