apiVersion: batch/v1
kind: CronJob
metadata:
  name: tide-app-cron
spec:
  schedule: "55 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tide-app
            image: gerops/tide-app:a3a9afb
            imagePullPolicy: IfNotPresent
            env:
            - name: TZ
              value: America/Los_Angeles
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-secret
          
---