apiVersion: batch/v1
kind: CronJob
metadata:
  name: tide-app-cron
spec:
  schedule: "15 7 * * *" # time must be in UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tide-app
            image: gerops/tide-app:ba0b2e6
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-secret
          
---