apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-app-cron
spec:
  schedule: "0 5,17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weather-app
            image: gerops/weather-app:<tag>
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-secret
          
---